name: Code Style

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-version: [ '7.4' ]

        name: PHP ${{ matrix.php-version }}

        steps:
            -   uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    extensions:
                    coverage: pcov
                    tools: composer:v1

            -   name: Install dependencies
                run: |
                    composer install --no-interaction

            -   name: Check code style
                run: |
                    php vendor/bin/php-cs-fixer --using-cache=no --diff --dry-run --stop-on-violation --verbose fix
